### ISSUE TITLE
باگ تعداد بالای کانفیگ

### ISSUE THREAD

**Issue by coldwater-10** [yebekhe/V2Hub#1]
من اینو فورک کردم ولی یه باگی که داره وقتی تعداد کانفیگای زیاد میدم دیگه کار نمیکنه بعد چند ساعت کنسل میشه اگه بشه مثلا 300 از سریع تریناشم جدا بشن برا کانفیگ کلش عالی میشه

**Comment by yebekhe** [comment]
خب تعداد بالای کانفیگ نده :)
قرار نیست هر چی لینک پیدا کردی بدی بهش میکس کنه که :)

**Comment by coldwater-10** [comment]
نمیشه کاری کنی کانفیگش کلش و بقیه چیزارو هم بسازه یا اگه تعداد کانفیگا زیاد بود مثل بردیا هر هزارتا جدا بشه از اون استفاده میکردم جدیدا پاک شده مخزنش
